In [16]:
import numpy as np
import pandas as pd

In [17]:
#输入数据的导入
df = pd.read_excel("shujuji.xlsx")
df.columns = ["id","temperature", "flow", "PH", "data_in_COD", "NH3_N","total_nitrogen","data_out_COD"]
temperature = df["temperature"]
temperature = np.array(temperature)
flow = df["flow"]
flow = np.array(flow)
ph=df["PH"]
ph=np.array(ph)
datainCOD = df["data_in_COD"]
datainCOD =np.array(datainCOD)
nh3n = df["NH3_N"]
nh3n = np.array(nh3n)
totalNitrogen = df["total_nitrogen"]
totalNitrogen = np.array(totalNitrogen)
cod = df["data_out_COD"]
cod = np.array(cod)
samplein = np.mat([temperature,flow,ph,datainCOD,nh3n,totalNitrogen])

In [18]:
print(samplein)

[[ 33.9     44.4     40.2    ...  24.1     48.7     47.7   ]
 [379.4386 374.3369 290.7272 ... 245.5469 233.4377 371.1947]
 [  5.67     5.03     7.11   ...   7.47     6.17     5.11  ]
 [362.0491 233.215  353.9716 ... 363.2505 309.1838 322.3266]
 [ 15.8     21.45    19.25   ...  22.09    20.07    20.24  ]
 [  7.32    12.93    10.85   ...  11.1     10.54     9.65  ]]


In [19]:
#数据归一化，将输入数据压缩至0到1之间，便于计算，后续通过反归一化恢复原始值
sampleinminmax = np.array([samplein.min(axis=1).T.tolist()[0],samplein.max(axis=1).T.tolist()[0]]).transpose()#对应最大值最小值

In [20]:
print(sampleinminmax)

[[ 18.      53.    ]
 [200.7118 499.8454]
 [  5.       8.    ]
 [200.6556 399.9792]
 [  8.26    29.87  ]
 [  5.04    15.    ]]


In [21]:
#待预测数据为cod
sampleout = np.mat([cod])
sampleoutminmax = np.array([sampleout.min(axis=1).T.tolist()[0],sampleout.max(axis=1).T.tolist()[0]]).transpose()
sampleinnorm = ((np.array(samplein.T)-sampleinminmax.transpose()[0])/(sampleinminmax.transpose()[1]-sampleinminmax.transpose()[0])).transpose()
sampleoutnorm = ((np.array(sampleout.T)-sampleoutminmax.transpose()[0])/(sampleoutminmax.transpose()[1]-sampleoutminmax.transpose()[0])).transpose()

In [22]:
print(sampleout)
print(sampleoutminmax)
print(sampleinnorm)
print(sampleoutnorm)

[[22.108  44.034  39.5237 21.0939 47.0766 36.5982 24.2228 29.5692 42.1015
  47.8751 29.66   44.1267 34.366  48.8093 26.6235 26.6321 29.3067 30.568
  39.8192 30.9357 29.0649 43.149  26.494  36.5425 39.5989 36.1831 30.9533
  32.8977 38.7983 48.964  32.0532 39.048  43.4939 43.2547 47.076  28.9256
  42.9691 40.1154 31.0628 25.1854 29.7085 21.3533 39.8145 45.6551 46.7678
  47.4597 28.1394 21.7935 34.3577 29.7212 39.5011 41.6992 25.5081 26.0384
  26.9562 23.0276 25.5306 47.9225 36.7649 35.5797 40.9821 38.0077 35.266
  31.9827 35.5248 29.4198 28.1858 31.2157 36.1816 22.9093 22.5665 45.1563
  27.0476 35.3497 39.7019 43.2006 33.312  23.7122 44.399  41.5874 28.453
  26.1381 24.0882 27.0615 22.8049 43.908  20.6331 48.6037 27.4177 44.5096
  24.3345 48.8936 49.7358 45.5005 38.3932 37.711  30.1745 28.7026 29.679
  45.3303 25.6193 38.0111 32.3283 22.5381 25.6578 40.7288 42.3414 48.4437
  24.1259 33.3232 40.9203 21.8861 43.9372 35.5016 35.5932 31.3077 29.6746
  35.1617 21.1087 26.3591 32.7571 37.9428 

In [23]:
sampleinnorm = sampleinnorm.transpose()
sampleoutnorm = sampleoutnorm.transpose()

In [24]:
print(sampleinnorm)
print(sampleoutnorm)

[[0.45428571 0.59748153 0.22333333 0.80970593 0.34891254 0.22891566]
 [0.75428571 0.58042661 0.01       0.16334945 0.61036557 0.79216867]
 [0.63428571 0.30092039 0.70333333 0.76918137 0.50856085 0.58333333]
 ...
 [0.17428571 0.1498832  0.82333333 0.81573331 0.63998149 0.60843373]
 [0.87714286 0.10940229 0.39       0.54448244 0.54650625 0.55220884]
 [0.84857143 0.56992227 0.03666667 0.61041944 0.55437298 0.46285141]]
[[0.06331671]
 [0.80023594]
 [0.64864756]
 [0.02923344]
 [0.90249583]
 [0.55032332]
 [0.13439382]
 [0.314083  ]
 [0.73528581]
 [0.92933292]
 [0.31713473]
 [0.80335153]
 [0.47530047]
 [0.9607308 ]
 [0.21507986]
 [0.2153689 ]
 [0.30526054]
 [0.34765205]
 [0.65857913]
 [0.36001022]
 [0.29713379]
 [0.77049164]
 [0.21072744]
 [0.54845128]
 [0.65117498]
 [0.53637207]
 [0.36060174]
 [0.42595182]
 [0.62426732]
 [0.96593017]
 [0.3975687 ]
 [0.63265958]
 [0.78208351]
 [0.77404415]
 [0.90247567]
 [0.29245201]
 [0.76444531]
 [0.66853423]
 [0.36428197]
 [0.16674621]
 [0.31876479]
 [0.03

In [60]:
S = 3  #模糊分级个数
T = 25  #规则生成层、归一化层节点数
iteration = 500  #迭代训练次数
learningrate = 0.01  #学习率

In [61]:
#c1、b1分别为李隶属度层的中心点与宽度向量、w1为输出层的权值，sampleinnorm.shape[1]代表输入数据的4个类别
c1 = np.random.uniform(low=-1, high=1, size=(S, sampleinnorm.shape[1]))
b1 = np.random.uniform(low=-1, high=1, size=(S, sampleinnorm.shape[1]))
w1 = np.random.uniform(low=0, high=1, size=(1, T))

In [62]:
sampleinnorm = np.mat(sampleinnorm)

In [63]:
#开始训练
for l in range(iteration):
    #print("the iteration is :",l+1)
    # 隶属度函数计算层计算输出
    Y = sampleoutnorm.copy()
    u1 = np.zeros((S, sampleinnorm.shape[1]))
    alpha = []
    alpha2 = []
    a1 = []
    for m in range(sampleinnorm.shape[0]):
        for i in range(S):
            for j in range(sampleinnorm.shape[1]):
                u1[i][j] = np.exp((-1) * ((sampleinnorm[m, j] - c1[i][j]) ** 2) / (b1[i][j] ** 2))
        # 规则生成层计算输出
        alpha1 = np.zeros((T, 1))
        for i in range(S):
            a = 1
            if i == 1:
                a = 8
            for p in range(S):
                b = 1
                if p == 1:
                    b = 4
                for q in range(S):
                    c = 1
                    if q == 1:
                        c = 2
                    for k in range(S):
                        alpha1[i * a + p * b + q * c + k] = u1[i][0] * u1[p][1] * u1[q][2] * u1[k][3]
        alpha.append(alpha1)
        # 归一化层计算输出
        alphasum = np.sum(alpha1)
        alpha2.append(alphasum)
        # 输出层计算输出
        a2 = np.dot(w1,alpha1)
        Y[m] = a2/alphasum
    #计算误差
    err = sampleoutnorm - Y
    loss = np.sum(np.abs(err))
    #print(" the loss is :",loss)
    if l==iteration-1:
        print("the iteration is :",l+1)
        print(" the loss is :",loss)
    #反向传播，分别计算参数w1、c1、b1的误差项
    deltaw1 = np.zeros((1,T))
    deltac1 = np.zeros((S, sampleinnorm.shape[1]))
    deltab1 = np.zeros((S, sampleinnorm.shape[1]))
    for m in range(sampleinnorm.shape[0]):
        changew1 = ((err[m] * alpha[m])/alpha2[m]).transpose()
        changec2 = np.zeros((S, sampleinnorm.shape[1]))
        changeb2 = np.zeros((S, sampleinnorm.shape[1]))
        z=np.zeros((S, sampleinnorm.shape[1]))
        v=np.zeros((S, sampleinnorm.shape[1]))
        for i in range(S):
            for j in range(sampleinnorm.shape[1]):
                z[i][j]=2*(sampleinnorm[m, j] - c1[i][j])/(b1[i][j] ** 2)
                v[i][j]=2*((sampleinnorm[m, j] - c1[i][j])**2)/(b1[i][j]**3)
        h = alpha[m]
        for u in range(T):
            changec1 = (((w1[:,u]-Y[m])*h[u,:])/alpha2[m])*z
            changec2 = changec1+changec2
            changeb1 = (((w1[:,u]-Y[m])*h[u,:])/alpha2[m])*v
            changeb2 = changeb1+changeb2
        deltac1 = deltac1 + changec2
        deltab1 = deltab1 + changeb2
        deltaw1 = deltaw1 + changew1
    #对三个参数进行更新
    c1 = c1 + learningrate * deltac1
    b1 = b1 + learningrate * deltab1
    w1 = w1 + learningrate * deltaw1

print('更新的w1:',w1)
print('更新的b1:',b1)
print('更新的c1:',c1)
 
#保存训练后的参数
np.save("c1.npy",c1)
np.save("b1.npy",b1)
np.save("w1.npy",w1)

the iteration is : 500
 the loss is : 60.72353199764358
更新的w1: [[0.06310242 0.33598593 0.3741046  0.30695865 0.5527255  0.68555375
  0.87250358 0.22899316 0.89034831 0.45434713 0.03473622 0.91515288
  0.20813252 0.76817442 0.49702147 0.49744055 1.0944954  0.13460148
  0.5816658  0.02724415 0.37701882 0.11130811 0.67471818 0.79463702
  0.18052581]]
更新的b1: [[ 0.50421136  0.04768261  0.51490338  0.83975097  0.94747674  0.52749621]
 [-0.24776487  0.70507268 -0.89190032  0.94978794 -0.50571287 -0.34993357]
 [ 0.16827705 -0.01215262  0.46566657 -0.41311576 -0.1007863  -0.94760938]]
更新的c1: [[-0.11763254 -0.49810567 -0.45849161  0.65728866 -0.68573809 -0.28883526]
 [ 0.52723463 -0.5568984  -0.27207985 -0.17373719 -0.81979591 -0.11522802]
 [ 0.2805495  -0.93148622 -0.82549264 -0.52229972 -0.36023927  0.89579269]]
